AWSTemplateFormatVersion: 2010-09-09

Parameters:
  UserName:
    Type: String
  UserArn:
    Type: String

Resources:
  UserStackSetRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${UserName}-CanStackSets"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref UserArn
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${UserName}-CanStackSetsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                Resource:
                  - !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/*/*'
                  - !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stackset-target/*'
                  - !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stackset/*:*'
